name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    
    # This is used to load Environment-level secrets, from the specified environment.
    # Instead, repository secrets are loaded by default.
    environment: production
    
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }} # Must be set as a GitHub secret
      DB_URL: ${{ secrets.DB_URL }} # Must be set as a GitHub secret
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      GOOGLE_MAPS_PLATFORM: ${{secrets.GOOGLE_MAPS_PLATFORM}}
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./backend
        cache: 'npm'
    - run: |
        cd ./backend
        npm install
    - run: |
        cd ./backend
        npm run build --if-present
    - run: |
        cd ./frontend
        npm run build
    - run: |
        cd ./backend
        npm test
  deploy:
    name: Deploy to render
    environment: production
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          cd ./frontend
          npm run build
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          apiKey: ${{secrets.RENDER_API_KEY}}
          serviceId: ${{secrets.RENDER_ID}}
          multipleDeployment: false
